### ISSUE TITLE
i got an infinite loop with "this is (pass/relay/block) and stable"

### ISSUE THREAD

**Issue by BananaBoi2130769** [PlasmaFlare/plasma-baba-mods#11] opened 2023-06-14 16:20 UTC
<img width="960" alt="image" src="https://github.com/PlasmaFlare/plasma-baba-mods/assets/119238116/38bdbe6f-9d38-4258-a01b-f22b3a471ba0">
<img width="316" alt="image" src="https://github.com/PlasmaFlare/plasma-baba-mods/assets/119238116/34024269-1938-483a-bfcb-d91de6c40928">
<img width="212" alt="image" src="https://github.com/PlasmaFlare/plasma-baba-mods/assets/119238116/2ecacdc6-7118-4c7c-acf6-79e7e550ae21">
<img width="234" alt="image" src="https://github.com/PlasmaFlare/plasma-baba-mods/assets/119238116/158b50ea-ea02-400b-9ee6-0b11cc2df869">

**Comment by PlasmaFlare** [comment] 2023-06-29 04:22
Looks like I somehow broke the rule that "Any objects that are `BLOCK/PASS/RELAY` cannot have other `THIS IS X` rules applied". The example below should not happen, since BLOCK should actively prevent the flag from being applied the PINK property.

This affects the original issue since baba is applied BLOCK/PASS/RELAY and STABLE at the same time, it causes a feedback loop between the two properties to repeatedly update their logic, which in turn causes an (unintended) infinite loop. The correct behavior should be that baba is only applied BLOCK/PASS/RELAY.

This seems to be a regression bug that dates back to as early as 1.5.0 release.

![image](https://github.com/PlasmaFlare/plasma-baba-mods/assets/6231645/5504ee62-4bc3-432b-9fe1-b24647958a94)

**Comment by PlasmaFlare** [comment] 2023-07-16 01:14
Should be fixed in latest release. https://github.com/PlasmaFlare/baba-mega-modpack/releases/tag/1.2.4

**Closed as completed by PlasmaFlare** 2023-07-16 01:14 UTC
